language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

install:
  - composer selfupdate
  - composer install

script:
  - phpunit --configuration phpunit.xml

notifications:
  email:
    recipients:
      - dev@omega-grid.org

    on_success: always
    on_failure: always
